type Event = {
  name: string;
  src: string;
  branch?: string;
  community?: string;
  category: string;
  type?: string;
  url: string;
};

export const eventList: Event[] = [
  {
    name: 'Women in Buisness',
    src: '/posters/poster-placeholder-1.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/women-in-business_.png',
    community: 'IEDC',
    category: 'TECHNICAL',
    type: 'EXPO',
    url: '',
  },
  {
    name: 'Idea Pitching',
    src: '/posters/poster-placeholder-2.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-18_at_22.29.37_c9735fa3.jpg',
    branch: 'ECE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://forms.gle/QkLi6aC2NWWVwB998',
  },
  {
    name: 'EV Drive',
    src: '/posters/poster-placeholder-3.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-18_at_22.29.13_5f8481ef.jpg',
    branch: 'EEE',
    category: 'TECHNICAL',
    type: 'WORKSHOP',
    url: 'https://forms.gle/i5GFyfR9xoziVT8i7',
  },
  {
    name: 'Hacknite',
    src: '/posters/poster-placeholder-4.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-18_at_22.29.08_791165df.jpg',
    branch: 'CSE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://hacknite.devfolio.co/',
  },
  {
    name: 'Technical Quiz',
    src: '/posters/poster-placeholder-5.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-18_at_14.33.25_d5a52fd6.jpg',
    branch: 'CE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://forms.gle/s3scptcDW9VxbnCY6',
  },
  {
    name: 'E-Football Tournament',
    src: '/posters/poster-placeholder-6.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-17_at_23.29.49_1e9e2961.jpg',
    branch: 'CSE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://forms.gle/L9n9FEmNxzUB95n67',
  },
  {
    name: 'BGMI Tournament',
    src: '/posters/poster-placeholder-7.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-17_at_23.29.38_60d3cb58.jpg',
    branch: 'CSE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://forms.gle/odm8Y8mHyXtLYxSFA',
  },
  {
    name: 'Capture The Flag: Cyber Challenge',
    src: '/posters/poster-placeholder-8.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-17_at_23.29.25_caaf84b1.jpg',
    community: 'IEEE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://forms.gle/zhCkh8Nt2pA5WfDJ8',
  },
  {
    name: 'Tech Talks: Life of an Entrepreneur',
    src: '/posters/poster-placeholder-9.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-17_at_23.29.05_52c66f9e.jpg',
    branch: 'CSE',
    category: 'TECHNICAL',
    type: 'TECH-TALK',
    url: '',
  },
  {
    name: 'Tech Talks: Cyber Security',
    src: '/posters/poster-placeholder-10.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-17_at_23.29.04_0ffb2014.jpg',
    branch: 'CSE',
    category: 'TECHNICAL',
    type: 'TECH-TALK',
    url: '',
  },
  {
    name: 'Non Destructive Testing',
    src: '/posters/poster-placeholder-11.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-15_at_22.37.09_e6b94974-min.jpg',
    branch: 'CE',
    category: 'TECHNICAL',
    type: 'WORKSHOP',
    url: 'https://forms.gle/BTtGLVhjbyoBa9B5A',
  },
  {
    name: 'Robo Soccer',
    src: '/posters/poster-placeholder-12.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/ROBO_SOCCER_1.1_2_hbKs789.png',
    branch: 'ECE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://forms.gle/DSPwqdXuQ7qLyPX99',
  },
  {
    name: "Da Vinci's Vault",
    src: '/posters/poster-placeholder-13.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-15_at_22.32.31_120de47f-min.jpg',
    branch: 'ME',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://forms.gle/Jn7rwTLzPwLAqAZ56',
  },
  {
    name: 'EV Hack',
    src: '/posters/poster-placeholder-14.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-15_at_22.32.30_63b4b103-min.jpg',
    branch: 'EEE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://forms.gle/BjCj72LnXnodi6GJ6',
  },
  {
    name: 'Project Expo',
    src: '/posters/poster-placeholder-15.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-13_at_22.00.36_d0ea6677-min.jpg',
    branch: 'EEE',
    category: 'TECHNICAL',
    type: 'EXPO',
    url: 'https://bit.ly/RegProjectExpo',
  },
  {
    name: 'Quake Proof Creation Challenge',
    src: '/posters/poster-placeholder-16.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-13_at_22.00.19_9e5926ea-min.jpg',
    branch: 'CE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://forms.gle/9Qh7oi5pXkAdQrfu6',
  },
  {
    name: 'Wrenching Wheels',
    src: '/posters/poster-placeholder-17.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-13_at_19.31.05_d777ea88-min.jpg',
    branch: 'ME',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://forms.gle/X96zHH2Pg6cho8hj7',
  },
  {
    name: 'Malhar: Musical Band Competition',
    src: '/posters/poster-placeholder-18.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-13_at_19.30.52_89e38456-min.jpg',
    category: 'CULTURAL',
    type: 'COMPETITION',
    url: 'https://docs.google.com/forms/d/e/1FAIpQLScPczdk4WDJgO2SGQFMicLwgQPMnkm4S1Z1DWmSXvuAHYNfjA/viewform',
  },
];

export const featuredEventList: Event[] = [
  {
    name: 'Designathon',
    src: '/posters/poster-placeholder-1.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/designathon.png',
    branch: 'CSE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://designathon24.vercel.app',
  },
  {
    name: 'Hacknite',
    src: '/posters/poster-placeholder-19.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/WhatsApp_Image_2024-02-18_at_22.29.08_791165df.jpg',
    branch: 'CSE',
    category: 'TECHNICAL',
    type: 'COMPETITION',
    url: 'https://hacknite.cce.edu.in/',
  },
  {
    name: 'Belfort of Wallstreet',
    src: '/posters/poster-placeholder-20.jpg',
    // src: 'https://dnbca6q7do6n.cloudfront.net/media/techletics24/Untitled-2.png',
    community: 'IEDC',
    category: 'TECHNICAL',
    type: 'TECH-TALK',
    url: 'https://bellfort-of-wallstreet.netlify.app/',
  },
];
