type Event = {
  name: string;
  src: string;
  url: string;
  registrationFee: number;
  date: string;
  coordinator: string;
  contact: string;
  maxTeamSize?: number;
};

export const eventList: Event[] = [
  {
    name: 'Women in Buisness',
    src: '/image/mohanlal.png',
    url: '',
    registrationFee: 0,
    date: '2025-02-20',
    coordinator: 'Ananya Nair',
    contact: '9876543210',
    maxTeamSize: 3,
  },
  {
    name: 'Idea Pitching',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/QkLi6aC2NWWVwB998',
    registrationFee: 100,
    date: '2025-02-21',
    coordinator: 'Rohit Menon',
    contact: '9123456789',
    maxTeamSize: 2,
  },
  {
    name: 'EV Drive',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/i5GFyfR9xoziVT8i7',
    registrationFee: 200,
    date: '2025-02-22',
    coordinator: 'Sneha Raj',
    contact: '9988776655',
  },
  {
    name: 'Hacknite',
    src: '/image/mohanlal.png',
    url: 'https://hacknite.devfolio.co/',
    registrationFee: 300,
    date: '2025-02-23',
    coordinator: 'Adithya Krishna',
    contact: '9638527410',
    maxTeamSize: 4,
  },
  {
    name: 'Technical Quiz',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/s3scptcDW9VxbnCY6',
    registrationFee: 50,
    date: '2025-02-24',
    coordinator: 'Meera Suresh',
    contact: '9012345678',
    maxTeamSize: 2,
  },
  {
    name: 'E-Football Tournament',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/L9n9FEmNxzUB95n67',
    registrationFee: 150,
    date: '2025-02-24',
    coordinator: 'Vishnu Das',
    contact: '9876501234',
    maxTeamSize: 2,
  },
  {
    name: 'BGMI Tournament',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/odm8Y8mHyXtLYxSFA',
    registrationFee: 100,
    date: '2025-02-25',
    coordinator: 'Akhil Raj',
    contact: '9745632189',
    maxTeamSize: 4,
  },
  {
    name: 'Capture The Flag: Cyber Challenge',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/zhCkh8Nt2pA5WfDJ8',
    registrationFee: 200,
    date: '2025-02-25',
    coordinator: 'Aparna Pillai',
    contact: '9023456789',
    maxTeamSize: 3,
  },
  {
    name: 'Tech Talks: Life of an Entrepreneur',
    src: '/image/mohanlal.png',
    url: '',
    registrationFee: 0,
    date: '2025-02-25',
    coordinator: 'Hari Prasad',
    contact: '9654321870',
  },
  {
    name: 'Tech Talks: Cyber Security',
    src: '/image/mohanlal.png',
    url: '',
    registrationFee: 0,
    date: '2025-02-26',
    coordinator: 'Nivedita B',
    contact: '9123409876',
  },
  {
    name: 'Non Destructive Testing',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/BTtGLVhjbyoBa9B5A',
    registrationFee: 250,
    date: '2025-02-26',
    coordinator: 'Deepak Varma',
    contact: '9812763450',
  },
  {
    name: 'Robo Soccer',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/DSPwqdXuQ7qLyPX99',
    registrationFee: 150,
    date: '2025-02-26',
    coordinator: 'Arjun M',
    contact: '9988774433',
    maxTeamSize: 3,
  },
  {
    name: "Da Vinci's Vault",
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/Jn7rwTLzPwLAqAZ56',
    registrationFee: 100,
    date: '2025-02-27',
    coordinator: 'Sreeja K',
    contact: '9098765432',
    maxTeamSize: 2,
  },
  {
    name: 'EV Hack',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/BjCj72LnXnodi6GJ6',
    registrationFee: 300,
    date: '2025-02-27',
    coordinator: 'Kiran T',
    contact: '9011223344',
    maxTeamSize: 5,
  },
  {
    name: 'Project Expo',
    src: '/image/mohanlal.png',
    url: 'https://bit.ly/RegProjectExpo',
    registrationFee: 0,
    date: '2025-02-27',
    coordinator: 'Sidharth K',
    contact: '9800765432',
    maxTeamSize: 4,
  },
  {
    name: 'Quake Proof Creation Challenge',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/9Qh7oi5pXkAdQrfu6',
    registrationFee: 100,
    date: '2025-02-28',
    coordinator: 'Rahul Dev',
    contact: '9776655443',
    maxTeamSize: 3,
  },
  {
    name: 'Wrenching Wheels',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/X96zHH2Pg6cho8hj7',
    registrationFee: 100,
    date: '2025-02-28',
    coordinator: 'Gayathri Menon',
    contact: '9765432109',
    maxTeamSize: 2,
  },
  {
    name: 'Malhar: Musical Band Competition',
    src: '/image/mohanlal.png',
    url: 'https://docs.google.com/forms/d/e/1FAIpQLScPczdk4WDJgO2SGQFMicLwgQPMnkm4S1Z1DWmSXvuAHYNfjA/viewform',
    registrationFee: 200,
    date: '2025-02-28',
    coordinator: 'Neha Raj',
    contact: '9556677889',
    maxTeamSize: 6,
  },
  {
    name: 'iRobotics Workshop',
    src: '/image/mohanlal.png',
    url: '',
    registrationFee: 250,
    date: '2025-03-01',
    coordinator: 'Jishnu S',
    contact: '9876501122',
  },
  {
    name: 'Build your Dreams',
    src: '/image/mohanlal.png',
    url: '',
    registrationFee: 0,
    date: '2025-03-01',
    coordinator: 'Alina George',
    contact: '9090909090',
  },
  {
    name: 'Clues and Cranks',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/vbsFfv9Dt94G8U7h9',
    registrationFee: 100,
    date: '2025-03-01',
    coordinator: 'Sanjay Krishna',
    contact: '9887766554',
    maxTeamSize: 3,
  },
  {
    name: 'Designathon',
    src: '/image/mohanlal.png',
    url: 'https://designathon24.devfolio.co/',
    registrationFee: 300,
    date: '2025-03-02',
    coordinator: 'Athira B',
    contact: '9812376540',
    maxTeamSize: 4,
  },
  {
    name: 'Drishti',
    src: '/image/mohanlal.png',
    url: 'https://forms.gle/A5483R6CCdL6JMPc6',
    registrationFee: 0,
    date: '2025-03-02',
    coordinator: 'Manu Raj',
    contact: '9321456780',
    maxTeamSize: 2,
  },
];
